version: '3'

vars:
  json_file: "vm_info.json"
  ignition_path: "ignition"

tasks:
  setup-loadbalancer:
    desc: "Setup the load balancer"
    cmds:
      - task: prepare-haproxy-config
      - task: prepare-keepalived-config
      - task: deploy-haproxy
      - task: deploy-keepalived

  prepare-haproxy-config:
    desc: "Prepare the HAProxy configuration"
    cmds:
      # Fetch IP information from the JSON file
      - |
        CONTROLLER_IPS=$(jq -r '.[] | select(.name | startswith("k8s-controller-")) | .ip' {{.json_file}})
        CONTROLLER_ARRAY=($CONTROLLER_IPS)

        controller_1_ip=${CONTROLLER_ARRAY[0]}
        controller_2_ip=${CONTROLLER_ARRAY[1]}
        controller_3_ip=${CONTROLLER_ARRAY[2]}

        mkdir -p haproxy/generated
        sed "s/controller_1_ip/$controller_1_ip/g; \
             s/controller_2_ip/$controller_2_ip/g; \
             s/controller_3_ip/$controller_3_ip/g" \
        haproxy/haproxy.cfg.template > haproxy/generated/haproxy.cfg

  prepare-keepalived-config:
    desc: "Prepare the Keepalived configuration"
    cmds:
      - |
        LB_IP=$(jq -r '.[] | select(.name | startswith("k8s-loadbalancer")) | .ip' {{.json_file}})
        mkdir -p haproxy/generated
        sed "s/loadbalancer_ip/$LB_IP/g" haproxy/keepalived.conf.template > haproxy/generated/keepalived.conf


  deploy-haproxy:
    desc: "Deploy HAProxy on the load balancer VM"
    cmds:
      - |
        LB_IP=$(jq -r '.[] | select(.name | startswith("k8s-loadbalancer")) | .ip' {{.json_file}})

        ssh -o "StrictHostKeyChecking=no" -i {{.ignition_path}}/id_rsa core@$LB_IP \
        mkdir -p /var/home/core/haproxy;

        scp -o "StrictHostKeyChecking=no" -i {{.ignition_path}}/id_rsa haproxy/generated/haproxy.cfg core@$LB_IP:/var/home/core/haproxy/haproxy.cfg

        ssh -o "StrictHostKeyChecking=no" -i {{.ignition_path}}/id_rsa core@$LB_IP \
        sudo podman run -d --name haproxy --restart=always -p 80:80 -p 443:443 -v /var/home/core/haproxy:/usr/local/etc/haproxy:ro docker.io/library/haproxy:latest

  deploy-keepalived:
    desc: "Deploy Keepalived on the load balancer VM"
    cmds:
      - |
        LB_IP=$(jq -r '.[] | select(.name | startswith("k8s-loadbalancer")) | .ip' {{.json_file}})

        ssh -o "StrictHostKeyChecking=no" -i {{.ignition_path}}/id_rsa core@$LB_IP \
        mkdir -p /var/home/core/keepalived;

        scp -o "StrictHostKeyChecking=no" -i {{.ignition_path}}/id_rsa haproxy/generated/keepalived.conf core@$LB_IP:/var/home/core/keepalived/keepalived.conf

        ssh -o "StrictHostKeyChecking=no" -i {{.ignition_path}}/id_rsa core@$LB_IP \
        sudo podman run -d --name keepalived --restart=always --cap-add=NET_ADMIN --cap-add=NET_BROADCAST --net=host -v /var/home/core/keepalived:/etc/keepalived:ro docker.io/osixia/keepalived:latest
